server:
  port: 6000
spring:
  datasource:
    username: root
    password: ${DB_PASSWD}
    url: jdbc:mysql://${CLOUD_HOST}:3306/nanguomall_wms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${CLOUD_HOST}:8848
      config:
        server-addr: ${CLOUD_HOST}:8848
  application:
    name: service-ware
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
