server:
  port: 8000
spring:
  datasource:
    username: root
    password: ${DB_PASSWD}
    url: jdbc:mysql://${CLOUD_HOST}:3306/nanguomall_sms
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
